*** parameterized modules

load ../lib/abstract/bag.maude
load ../lib/abstract/pair.maude


*** machine
 
load ../role/machine.maude
load ../lib/view/machine.maude

*** connection

load ../role/connection.maude
load ../lib/view/connection.maude

*** collection

load ../lib/collection/connections.maude
load ../lib/collection/machines.maude

*** environment

load ../object/cloud.maude
load ../object/script.maude
