load ./pred/preds.maude
load ./instance/success.maude
load ./instance/less_machines.maude
load ./instance/wrong_conf.maude

mod CHECK is
 pr SUCCESS .
 pr LESS_MACHINES .
 pr WRONG_CONF .
 
 inc PREDS .
 inc MODEL-CHECKER .
 inc LTL-SIMPLIFIER .
 ops converged : -> Formula .
 eq  converged = (<> ([] configured)) .
endm

red in CHECK : modelCheck(success, converged) .
red in CHECK : modelCheck(less-machines, converged) .
red in CHECK : modelCheck(wrong-conf, converged) .

quit .
