*** parameterized modules

load ./abstract/bag.maude
load ./abstract/pair.maude


*** machine
 
load ./concrete/machine.maude
load ./view/machine.maude

*** connection

load ./concrete/connection.maude
load ./view/connection.maude

*** collection

load ./collection/connections.maude
load ./collection/machines.maude



*** test reduces

***(
var d : Nat .
vars a b : Machine .
red [a,b] .
)







quit
